# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               UHN Development
tagline:             ''
description:         'A development blog dedicated to discussing solutions to some of the technical challenges we’ve come across here at UHN.'
url:                 http://uhndev.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Kevin Chan
  url:               https://github.com/khchan
  email:             kevin.chan@rmp.uhn.ca

# Custom vars
version:             1.0.0
